all:
  children:
    allservers:
      children:
        appserver:
          hosts:
            appserver1:
              ansible_host: 35.159.127.41
              ansible_ssh_private_key_file: ~/.ssh/key.pem
              ansible_user: ec2-user
        dbserver:
          hosts:
            dbserver1:
              ansible_host: 54.93.216.124
              ansible_ssh_private_key_file: ~/.ssh/key.pem
              ansible_user: ec2-user
        webserver:
          hosts:
            webserver1:
              ansible_host: 3.68.218.161
              ansible_ssh_private_key_file: ~/.ssh/key.pem
              ansible_user: ec2-user
    ungrouped: {}
